### ISSUE TITLE
Cannot fetch balance

### ISSUE THREAD

**Issue by gregordoltar** [oyvindberg/binance-scala-api#3]
There is a problem fetching account balance. Problem seems to be in Decoders.scala
a,f,l are not used.

implicit lazy val AssetBalanceDecoder: Decoder[AssetBalance] =
-    Decoder.forProduct3("a", "f", "l")(AssetBalance.apply)
+    Decoder.forProduct3("asset", "free", "locked")(AssetBalance.apply)

**Comment by oyvindberg** [comment]
Oh, that's interesting. I remember seeing something similar when i worked on this, where the same case class had two different json encodings. I propose we just duplicate the case class so there is no way of mixing it up again.

I'll be honest, I'm not working on this right now, though I intend to continue relatively soon. Do you have a chance to create a PR @gregordoltar ?

**Comment by BRZRKRR** [comment]
@oyvindberg @gregordoltar Hey guys! Just faced the same problem. Any ideas how to fix this? I'm new to circe, so I'm not sure where to start :D

**Comment by gregordoltar** [comment]
@oyvindberg 

Are you sure that same case class has two different json encodings ? I did not see this elsewhere. It is however also true that I only used a small portion from your API.

I will create PR so my changes are in and saved. You can then merge them when time is right.

@VecnaSecrets 

You need to replace line:

Decoder.forProduct3("a", "f", "l")(AssetBalance.apply)
with
Decoder.forProduct3("asset", "free", "locked")(AssetBalance.apply)

in Decoders.scala file

**Comment by oyvindberg** [comment]
@gregordoltar The short names, if i understand and remember correctly, are used for websocket calls. there is a test for it in `UserDataUpdateEventDeserializerTest` where you can see it.

I think the websocket calls are meant to handle loads of events so they are compressed in that form. 

There are three ways to fix this problem:
- selective imports in the right scope, which is horribly prone to errors
- exposing decoders for [tagged] case classes, which carries a mental hoverhead
- copy/paste the case class with a new name, so implicits are unambigous since they are different.

I propose we do the the third option. Would you have time to do it?

**Comment by gregordoltar** [comment]
I have just created a new pull request (https://github.com/oyvindberg/binance-scala-api/pull/5)  with this quickfix. But to be honest I dislike the fix.

If all websocket classes are optimised then we would probably need to somehow group websocket (optimised) classes together with WS prefix:

WSAssetBalance
...

But this should be done for all classes that are websocket optimised.

**Comment by oyvindberg** [comment]
Completely get your point, it's not really satisfactory that serialization details leak into the domain layer. Let's revisit down the road - for one thing renaming all those classes should be simple, and we might find a better, simple encoding for this :)

Meanwhile I'll just merge it, i assume you've tested it :)

Thanks!

**Comment by oyvindberg** [comment]
Also I feel obligated to mention @gregordoltar and @VecnaSecrets that I intend to rewrite this library, most probably using http4s with an effect type from cats-effect (pending proper websocket client support - not sure of current status there). I recommend you plan accordingly, whether it be forking the library or joining the effort :)
